gsap.from("#cartoonicorn", { stroke: "black", opacity: 0, duration: 3, scale: 0, strokeWidth: 10 })
gsap.to("#fairy", { opacity: 0.5, fill: "gold" })
gsap.to("#fairy", { opacity: 1, fill: "yellow", repeat: -1 }, 2)
gsap.to("#unicorn", { rotate: -5, transformOrigin: "50% 50%", repeat: 4 })

let unicornAnimate = gsap.timeline()

.to("#hair1", { duration: 4, fill: "purple", repeat: -1 })
    .to("#hair1", { duration: 5, fill: "green", repeat: -1 })
    .to("#hair2", { duration: 3, fill: "orange", repeat: -1 })
    .to("#hair3", { duration: 5, fill: "red", repeat: -1 })
    .to("#hair4", { duration: 2, fill: "violet", repeat: -1 }, 2)
    .to("#hair5", { duration: 6, fill: "brown", repeat: -1 })
    .to("#ear", { fill: "purple", opacity: .4 }, 2)
    .fromTo("#heart", { x: -10, scale: 1.3, fill: "red" }, { scale: 1, duration: 3, x: 0, ease: "elastic", fill: "pink" })
    .fromTo("#horn1", { fill: "pink" }, { duration: 2.5, fill: "violet", repeat: -1 }, 2)
    .fromTo("#horn2", { fill: "pink" }, { duration: 2, fill: "purple", repeat: -1 }, 1)
    .fromTo("#horn3", { fill: "pink" }, { duration: 1.5, fill: "plum", repeat: -1 }, 2)
    .fromTo("#horn4", { fill: "pink" }, { duration: 1, fill: "violet", repeat: -1 }, 2)
    .fromTo("#horn5", { fill: "pink" }, { duration: .5, fill: "purple", repeat: -1 }, 2)
    .fromTo("#unicornBody", { fill: "pink", x: 10 }, { x: 0, duration: 5, ease: "elastic", fill: "plum", reapeat: -1 }, 4)